### ISSUE TITLE
Text component is missing

### ISSUE THREAD

**Issue by nguyenvanduocit** [ownego/polaris-vue#380]
I think you guys forgot to import Text component into Button component

![image](https://github.com/ownego/polaris-vue/assets/1256953/0cc9d361-24fe-42e3-8286-b1026c3e609d)

**Comment by nguyenvanduocit** [comment]
I guess that you guys alway use PolarisVue as a plugin, so you never see the issue.

**Comment by juzser** [comment]
@nguyenvanduocit Good point, let me check around.

**Comment by juzser** [comment]
Hopefully I fixed them all on [v2.1.2](https://github.com/ownego/polaris-vue/releases/tag/v2.1.2)

**Comment by nguyenvanduocit** [comment]
Thanks for works

**Comment by nguyenvanduocit** [comment]
Look like there are some issue in the build action

**Comment by juzser** [comment]
Fixed.

**Comment by nguyenvanduocit** [comment]
Look like the resolveComponent still not work, the issue is inside component Banner:

![image](https://github.com/ownego/polaris-vue/assets/1256953/e49a62eb-f326-4df9-aae3-acdd916a1bdc)

![image](https://github.com/ownego/polaris-vue/assets/1256953/f8cdb851-f305-4e4e-8732-6cf41ffcb9c3)
 
 this function only work with registered components, consider use dynamic import instead.

**Comment by juzser** [comment]
Fixed on [v2.1.3](https://github.com/ownego/polaris-vue/releases/tag/v2.1.3) 

Thank you.
